// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSxhLKD_ywEe0myUHYEw6qUVLpf-VsK24',
    appId: '1:895291640860:web:fecbaeeb588e4c9c6fa3d9',
    messagingSenderId: '895291640860',
    projectId: 'virtualdressroom-7c625',
    authDomain: 'virtualdressroom-7c625.firebaseapp.com',
    storageBucket: 'virtualdressroom-7c625.appspot.com',
    measurementId: 'G-6FM4H38LVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApe2M4XnvhNh9FVSad6s9gEb4QeqcCzRE',
    appId: '1:895291640860:android:c54fca47291a02956fa3d9',
    messagingSenderId: '895291640860',
    projectId: 'virtualdressroom-7c625',
    storageBucket: 'virtualdressroom-7c625.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88IZs0C9-qlD0E5CCeAics_9hD_ZJrDo',
    appId: '1:895291640860:ios:cceb409acd464bc26fa3d9',
    messagingSenderId: '895291640860',
    projectId: 'virtualdressroom-7c625',
    storageBucket: 'virtualdressroom-7c625.appspot.com',
    iosBundleId: 'com.example.virtualDressRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA88IZs0C9-qlD0E5CCeAics_9hD_ZJrDo',
    appId: '1:895291640860:ios:cceb409acd464bc26fa3d9',
    messagingSenderId: '895291640860',
    projectId: 'virtualdressroom-7c625',
    storageBucket: 'virtualdressroom-7c625.appspot.com',
    iosBundleId: 'com.example.virtualDressRoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSxhLKD_ywEe0myUHYEw6qUVLpf-VsK24',
    appId: '1:895291640860:web:41d286f1eb3f8f846fa3d9',
    messagingSenderId: '895291640860',
    projectId: 'virtualdressroom-7c625',
    authDomain: 'virtualdressroom-7c625.firebaseapp.com',
    storageBucket: 'virtualdressroom-7c625.appspot.com',
    measurementId: 'G-MDWNK2YQ5Y',
  );
}
